
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Fri Apr 06 23:49:06 EDT 2018
//----------------------------------------------------

package parser;

/** CUP generated class containing symbol constants. */
public class Sym {
  /* terminals */
  public static final int MULT = 26;
  public static final int INHERITS = 7;
  public static final int POOL = 10;
  public static final int CASE = 13;
  public static final int LPAREN = 34;
  public static final int SEMI = 32;
  public static final int MINUS = 25;
  public static final int STR_CONST = 39;
  public static final int RPAREN = 35;
  public static final int NOT = 20;
  public static final int TYPEID = 42;
  public static final int LT = 28;
  public static final int IN = 6;
  public static final int COMMA = 31;
  public static final int CLASS = 2;
  public static final int FI = 4;
  public static final int DIV = 24;
  public static final int LOOP = 9;
  public static final int PLUS = 23;
  public static final int ASSIGN = 19;
  public static final int IF = 5;
  public static final int DOT = 29;
  public static final int LE = 21;
  public static final int OF = 15;
  public static final int EOF = 0;
  public static final int INT_CONST = 40;
  public static final int NEW = 17;
  public static final int error = 1;
  public static final int ISVOID = 18;
  public static final int EQ = 27;
  public static final int ERROR = 22;
  public static final int COLON = 33;
  public static final int NEG = 30;
  public static final int LBRACE = 37;
  public static final int ELSE = 3;
  public static final int DARROW = 16;
  public static final int WHILE = 12;
  public static final int ESAC = 14;
  public static final int LET = 8;
  public static final int RBRACE = 38;
  public static final int THEN = 11;
  public static final int BOOL_CONST = 41;
  public static final int OBJECTID = 43;
  public static final int AT = 36;
}

